package com.endang.restEvoting.model;


/**
 * Suara generated by hbm2java
 */
public class Suara {

	private Integer idSuara;
	private int idKandidat;
	private String namaKandidat;
	private int jumlahSuara;

	public Suara() {
	}

	public Suara(Integer idSuara, int idKandidat, int jumlahSuara) {
		super();
		this.idSuara = idSuara;
		this.idKandidat = idKandidat;
		this.jumlahSuara = jumlahSuara;
	}
	
	public Suara(Integer idSuara, int idKandidat, String namaKandidat,
			int jumlahSuara) {
		super();
		this.idSuara = idSuara;
		this.idKandidat = idKandidat;
		this.namaKandidat = namaKandidat;
		this.jumlahSuara = jumlahSuara;
	}

	public Integer getIdSuara() {
		return this.idSuara;
	}

	public void setIdSuara(Integer idSuara) {
		this.idSuara = idSuara;
	}

	public int getIdKandidat() {
		return idKandidat;
	}

	public void setIdKandidat(int idKandidat) {
		this.idKandidat = idKandidat;
	}

	public int getJumlahSuara() {
		return this.jumlahSuara;
	}

	public void setJumlahSuara(int jumlahSuara) {
		this.jumlahSuara = jumlahSuara;
	}

	public String getNamaKandidat() {
		return namaKandidat;
	}

	public void setNamaKandidat(String namaKandidat) {
		this.namaKandidat = namaKandidat;
	}
	
}
