package com.endang.restEvoting.model;

/**
 * Suara generated by hbm2java
 */
public class Suara {

	private int idSuara;
	private int idKandidat;
	private String namaKandidat;
	private int jumlahSuara;
	private String response;

	public Suara() {
	}

	public Suara(int idSuara, int idKandidat, String namaKandidat,
			int jumlahSuara, String response) {
		super();
		this.idSuara = idSuara;
		this.idKandidat = idKandidat;
		this.namaKandidat = namaKandidat;
		this.jumlahSuara = jumlahSuara;
		this.response = response;
	}

	public int getIdSuara() {
		return idSuara;
	}

	public void setIdSuara(int idSuara) {
		this.idSuara = idSuara;
	}

	public int getIdKandidat() {
		return idKandidat;
	}

	public void setIdKandidat(int idKandidat) {
		this.idKandidat = idKandidat;
	}

	public String getNamaKandidat() {
		return namaKandidat;
	}

	public void setNamaKandidat(String namaKandidat) {
		this.namaKandidat = namaKandidat;
	}

	public int getJumlahSuara() {
		return jumlahSuara;
	}

	public void setJumlahSuara(int jumlahSuara) {
		this.jumlahSuara = jumlahSuara;
	}

	public String getResponse() {
		return response;
	}

	public void setResponse(String response) {
		this.response = response;
	}

}
