package com.endang.evotingrest.model;

/**
 * Option generated by hbm2java
 */

public class Option {

	private Integer idOption;
	private String jenisOption;
	private String valueOption;

	public Option() {
	}

	public Option(String jenisOption, String valueOption) {
		this.jenisOption = jenisOption;
		this.valueOption = valueOption;
	}

	public Integer getIdOption() {
		return this.idOption;
	}

	public void setIdOption(Integer idOption) {
		this.idOption = idOption;
	}

	public String getJenisOption() {
		return this.jenisOption;
	}

	public void setJenisOption(String jenisOption) {
		this.jenisOption = jenisOption;
	}

	public String getValueOption() {
		return this.valueOption;
	}

	public void setValueOption(String valueOption) {
		this.valueOption = valueOption;
	}

}
